### ISSUE TITLE
rstan package installs but doesn't load properly

### ISSUE THREAD

**Issue by ntaback** [utoronto-2i2c/jupyterhub-deploy#30]
@yuvipanda 
`install.packages("rstan")`
gives no errors.  But, when trying to load the library there is an error
`> library(rstan)`
Error: package or namespace load failed for ‘rstan’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/r/V8/libs/V8.so':
  libnode.so.64: cannot open shared object file: No such file or directory

**Comment by whositwhatnow** [comment]
looks like you need the nodejs libraries package installed in the image

**Comment by yuvipanda** [comment]
Thank you for reporting it here!

Turns out it needed nodejs from apt, not from conda (as I was doing earlier). See 3625086136540b0d3cc6b8b71d00b0d8584c52e7 for some more info.

I've installed `rstan` into the base image, and can import it now. Let me know if you run into issues with it.

**Comment by ntaback** [comment]
strange @yuvipanda .  I'm still getting the same error, and `rstan` doesn't seem to be installed in base image. Also, when I install it I still get

> library(rstan)
Loading required package: StanHeaders
Error: package or namespace load failed for ‘rstan’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/r/V8/libs/V8.so':
  libnode.so.64: cannot open shared object file: No such file or directory

**Comment by yuvipanda** [comment]
Can you check now?

**Comment by ntaback** [comment]
`rstan` wasn't installed.  when I installed I got the same error.

**Comment by yuvipanda** [comment]
ok, I think I've fixed it now :)

**Comment by ntaback** [comment]
Thanks,  @yuvipanda .  Unfortunately, it's still not working.  

The package loads, but I get an error when I try to fit a basic model.  This example, works on my computer.

The file `schools.stan` contains

```
data {
  int<lower=0> J;          // number of schools 
  real y[J];               // estimated treatment effects
  real<lower=0> sigma[J];  // s.e. of effect estimates 
}
parameters {
  real mu; 
  real<lower=0> tau;
  vector[J] eta;
}
transformed parameters {
  vector[J] theta;
  theta = mu + tau * eta;
}
model {
  target += normal_lpdf(eta | 0, 1);
  target += normal_lpdf(y | theta, sigma);
}
```

The R script `stanexample.R` is 

```
schools_data <- list(
  J = 8,
  y = c(28,  8, -3,  7, -1,  1, 18, 12),
  sigma = c(15, 10, 16, 11,  9, 11, 10, 18)
)

library(rstan)
fit1 <- stan(
  file = "schools.stan",  # Stan program
  data = schools_data,    # named list of data
  chains = 4,             # number of Markov chains
  warmup = 1000,          # number of warmup iterations per chain
  iter = 2000,            # total number of iterations per chain
  cores = 1,              # number of cores (could use one per chain)
  refresh = 0             # no progress shown
)
print(fit1)
```

I get the error

```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  /opt/r/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type’ {aka ‘__vector(2) double’} [-Wignored-attributes]  960 |   enum {      |        ^g++: fatal error: Killed signal terminated program cc1pluscompilation terminated.make: *** [/usr/lib/R/etc/Makeconf:176: file41608941d2.o] Error 1
In addition: Warning message:
In readLines(file, warn = TRUE) :
  incomplete final line found on '/home/jovyan/schools.stan'
Error in sink(type = "output") : invalid connection
```

**Comment by yuvipanda** [comment]
@ntaback hmm, looking around in the rstan world, maybe https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuration-of-the-c-toolchain will help? Can you try that?

**Comment by ntaback** [comment]
success @yuvipanda !  This worked.

```
dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars"))
if (!file.exists(M)) file.create(M)
cat(if( grepl("^darwin", R.version$os)) "\nCXX14FLAGS=-O3 -march=native -mtune=native -arch x86_64 -ftemplate-depth-256" else 
  if (.Platform$OS.type == "windows") "\nCXX14FLAGS=-O3 -mtune=native -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2" else
    "CXX14FLAGS = -fPIC",
  file = M, sep = "\n", append = TRUE)
```

Would it be possible to set `CXX14FLAGS = -fPIC` for the system so users don't have to go through this step?

**Comment by yuvipanda** [comment]
Awesome. I'll try to do that tomorrow :)

**Comment by yuvipanda** [comment]
Didn't get to it today unfortunately. Will try to do this tomorrow!

**Comment by yuvipanda** [comment]
https://trac.sagemath.org/ticket/18691 is related. There's an existing Makevars file that comes from the R package, so it's a bit hard to replace that. I don't want to add to ~/.R either, since that's in the user's home directories.

We should create a new file, and try pointing `R_MAKEVARS_USER` to it.
